image: lwch/natpass-builder:1.19

stages:
  - lint
  - build
  - release

lint:
  stage: lint
  script:
    - go install golang.org/x/lint/golint@latest
    - golint -set_exit_status code/...
    - go install github.com/gordonklaus/ineffassign@latest
    - ineffassign ./...

build:
  stage: build
  script:
    - go run contrib/build/build_all.go

release:
  stage: release
  artifacts:
    paths:
      - release/*